name: Publish Release Nightly

on:
  push:
    branches:
      - main

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetching tags
        run: git fetch --tags -f || true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Doker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            yurytomaz/whatsapp-api-baileys:nightly

      - name: Generate Changelog
        id: generate_changelog
        run: |
          changelog=$(npm run changelog:preview --silent)
          echo "${changelog}" > $GITHUB_WORKSPACE/changelog.txt

      - name: Create Release
        uses: meeDamian/github-release@2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          commitish: ${{ github.sha }}
          name: ${{ github.ref_name }}
          body: $GITHUB_WORKSPACE/changelog.txt
          draft: false
          allow_override: true
          prerelease: true